# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e3110d5f2fe1a4719670c45003d4b70215854f192c5923af788a73a940802aa4c3fe03cd1b814682cc197e118727b818133db67c6b340ad2eef3f59447bf70c4

test:
  secret_key_base: 1183c0b284ae1229f97e4fc4a23b7dee207e69c651a09b52c04badfd0d7e8d887136ee97badd637cb81ead9ccf7021617a285104f3acdf5868de4adad0617555

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
